### ISSUE TITLE
Card almost invisible

### ISSUE THREAD

**Issue by NafieAlhilaly** [X7md/x7md.github.io#2]
The card component is hard to see and needs a visual enhancement.
almost can not see its border
![Screenshot 2022-05-01 155415](https://user-images.githubusercontent.com/16656005/166146927-92aa3194-197f-4184-a780-98a05f18b788.jpg)

this is a proposal [PR](#3) to show my suggested enhancements.

**Comment by NafieAlhilaly** [comment]
#3

**Comment by X7md** [comment]
Done.
